### PR TITLE
Semantic mirror

### PR DESCRIPTION
**Pull request by ShaneDelmore**
Add scalahost semantic mirror

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
The efficiency there was absolutely amazing.

**Comment by ghost** [comment]
It was pre-reviewed - we wanted to merge quickly to move the repo over to Typelevel

**Comment by ChristopherDavenport** [comment]
Very nice. I'm excited about both of these projects, if you guys need any help let me know. Without any issues it's hard to take aim at where to help you.

**Comment by ghost** [comment]
@ChristopherDavenport Awesome!

We have a few more "bits" to get right regarding splitting code out from scalafix and getting the build working with whatever that will be.

But we some thing already we/I can add to issues - reviewing the README for clarity would be useful as a minor start!

**Pull request merged**
